# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-22 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180921_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='email',
        ),
        migrations.RemoveField(
            model_name='events',
            name='member_type',
        ),
        migrations.RemoveField(
            model_name='events',
            name='mobile',
        ),
    ]
