# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-09-21 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='file',
            field=models.FileField(max_length=250, upload_to=b''),
        ),
    ]
